Repository ChildMindInstitute/mindlogger-app, pull requests merged in 2021-02, with the labels that each got.

#1528 Add custom tooltip
  CHANGELOG.md
  README.md
  android/app/build.gradle
  app/services/helper.js
  app/widgets/MultiSelect.js
  app/widgets/Radio.js
  app/widgets/TooltipBox.js
  app/widgets/index.js
  ios/MDCApp/Info.plist
  package.json
Labels: Android, Epic, ReactNative, bug, iOS, mobileapp

#1532 Bugfix/25
  CHANGELOG.md
  README.md
  android/app/build.gradle
  app/components/core/MarkdownScreen.js
  app/themes/activityTheme.js
  ios/MDCApp/Info.plist
  package.json
  yarn.lock
Labels: CMI Milestone 3

#1548 Fix prizes activity screen text align
  app/widgets/RadioPrizes.js
Labels: CMI Milestone 3, ReactNative, bug, iOS, mobileapp

#1533 Full screen on Tablets
  app.json
  ios/MDCApp.xcodeproj/project.pbxproj
Labels: CMI Milestone 3, ReactNative, bug

#1534 Fix AudioImageRecord Item
  CHANGELOG.md
  app/components/screen/Widget.js
Labels: CMI Milestone 3

#1535 Ability to change the length of Audio can be recorded by user
  CHANGELOG.md
  README.md
  android/app/build.gradle
  app/widgets/AudioRecord/AudioImageRecord.js
  app/widgets/AudioRecord/index.js
  ios/MDCApp/Info.plist
  package.json
Labels: CMI Milestone 3

#1554 Accumulate Negative Tokens Option
  app/models/json-ld.js
  app/models/response.js
Labels: Android, CMI Milestone 3, JavaScript, ReactNative, enhancement, frontend, iOS, mobileapp

#1556 Fix/tooltip
  app/widgets/TooltipBox.js
  package.json
  yarn.lock
Labels: Android, ReactNative, bug, mobileapp

#1476 Add feature to play video from library on Android
  android/app/build.gradle
  app/widgets/Camera.js
  package.json
  yarn.lock
Labels: Android, CMI Milestone 3, ReactNative, enhancement, mobileapp
